import java.util.*;

class Solution {
    public int minimumDistance(int[] nums) {
            int n = nums.length;
                    
                            // Store indices for each number
                                    Map<Integer, List<Integer>> map = new HashMap<>();
                                            
                                                    for (int i = 0; i < n; i++) {
                                                                map.putIfAbsent(nums[i], new ArrayList<>());
                                                                            map.get(nums[i]).add(i);
                                                                                    }
                                                                                            
                                                                                                    int minDist = Integer.MAX_VALUE;
                                                                                                            
                                                                                                                    // Check each number
                                                                                                                            for (List<Integer> list : map.values()) {
                                                                                                                                        int size = list.size();
                                                                                                                                                    
                                                                                                                                                                // Need at least 3 same elements
                                                                                                                                                                            if (size < 3) continue;
                                                                                                                                                                                        
                                                                                                                                                                                                    // Try all triples
                                                                                                                                                                                                                for (int i = 0; i < size - 2; i++) {
                                                                                                                                                                                                                                for (int j = i + 1; j < size - 1; j++) {
                                                                                                                                                                                                                                                    for (int k = j + 1; k < size; k++) {
                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                    int dist = Math.abs(list.get(i) - list.get(j)) +
                                                                                                                                                                                                                                                                                                                                       Math.abs(list.get(j) - list.get(k)) +
                                                                                                                                                                                                                                                                                                                                                                          Math.abs(list.get(k) - list.get(i));
                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                          minDist = Math.min(minDist, dist);
                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return minDist == Integer.MAX_VALUE ? -1 : minDist;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }